/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos/novo'
import { Route as ProjetosIdUnidadesRouteImport } from './routes/projetos/$id/unidades'
import { Route as ProjetosIdCalculoRouteImport } from './routes/projetos/$id/calculo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdUnidadesRoute = ProjetosIdUnidadesRouteImport.update({
  id: '/projetos/$id/unidades',
  path: '/projetos/$id/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdCalculoRoute = ProjetosIdCalculoRouteImport.update({
  id: '/projetos/$id/calculo',
  path: '/projetos/$id/calculo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/projetos/$id/calculo': typeof ProjetosIdCalculoRoute
  '/projetos/$id/unidades': typeof ProjetosIdUnidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/projetos/$id/calculo': typeof ProjetosIdCalculoRoute
  '/projetos/$id/unidades': typeof ProjetosIdUnidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/projetos/$id/calculo': typeof ProjetosIdCalculoRoute
  '/projetos/$id/unidades': typeof ProjetosIdUnidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projetos/novo'
    | '/projetos/$id/calculo'
    | '/projetos/$id/unidades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projetos/novo'
    | '/projetos/$id/calculo'
    | '/projetos/$id/unidades'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projetos/novo'
    | '/projetos/$id/calculo'
    | '/projetos/$id/unidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  ProjetosIdCalculoRoute: typeof ProjetosIdCalculoRoute
  ProjetosIdUnidadesRoute: typeof ProjetosIdUnidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id/unidades': {
      id: '/projetos/$id/unidades'
      path: '/projetos/$id/unidades'
      fullPath: '/projetos/$id/unidades'
      preLoaderRoute: typeof ProjetosIdUnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id/calculo': {
      id: '/projetos/$id/calculo'
      path: '/projetos/$id/calculo'
      fullPath: '/projetos/$id/calculo'
      preLoaderRoute: typeof ProjetosIdCalculoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
  ProjetosIdCalculoRoute: ProjetosIdCalculoRoute,
  ProjetosIdUnidadesRoute: ProjetosIdUnidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
